# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.18.1'
  displayName: 'Install Node.js'

- script: |
    npm run frontend:install
    npm run backend:install
    npm run frontend:build
    npm run backend:build
    npm run frontend:test
    npm run backend:test
  displayName: 'npm install and build'
